# Generated by Django 5.0.6 on 2024-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='candidato',
            name='apellidoCandidato',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='candidato',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nombreCandidato',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='candidato',
            name='rut',
            field=models.CharField(default='Desconocido', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='Desconocido', max_length=200, primary_key=True, serialize=False),
        ),
    ]
