# Generated by Django 4.2.13 on 2024-06-28 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_remove_candidato_id_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('roller', 'Roller'), ('skate', 'Skate'), ('surf', 'Surf')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='candidato',
            name='apellidoCandidato',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombreCandidato',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rut',
            field=models.CharField(default=' ', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default=' ', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto')),
            ],
        ),
    ]
