# Generated by Django 4.2.13 on 2024-07-01 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mi_aplicacion', '0003_producto_alter_candidato_apellidocandidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('roller', 'Roller'), ('skate', 'Skate'), ('surf', 'Surf'), ('accesoriosurf', 'AccesorioSurf'), ('accesorioskate', 'AccesorioSkate'), ('accesorioroller', 'AccesorioRoller')], max_length=20),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.ManyToManyField(through='mi_aplicacion.CarritoItem', to='mi_aplicacion.producto')),
                ('usuario', models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.carrito'),
        ),
    ]
